# Generated by Django 3.0.9 on 2020-08-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.TextField()),
                ('productCategory', models.TextField()),
                ('productBuyDate', models.TimeField()),
                ('productExpDate', models.TimeField()),
            ],
        ),
    ]
