# Generated by Django 3.0.9 on 2020-08-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlist',
            name='productImage',
            field=models.TextField(blank=True),
        ),
    ]
