# Generated by Django 3.0.9 on 2020-08-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='productBuyDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='productExpDate',
            field=models.DateField(help_text='Food Expiration Dates', verbose_name='Expiring day'),
        ),
    ]
