# Generated by Django 3.0.9 on 2020-08-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0002_auto_20200831_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlist',
            name='productPic',
        ),
        migrations.RemoveField(
            model_name='foodlist',
            name='productPicUrl',
        ),
        migrations.AddField(
            model_name='foodlist',
            name='productImg',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Recipe image'),
        ),
    ]
