# Generated by Django 3.0.9 on 2020-08-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0002_auto_20200808_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='productBuyDate',
            field=models.DateField(help_text='When you bought it', verbose_name='Buying day'),
        ),
    ]
