# Generated by Django 3.0.9 on 2020-08-08 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0003_auto_20200808_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlist',
            name='productToday',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
