# Generated by Django 3.0.9 on 2020-08-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0003_auto_20200831_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='productImg',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Recipe image'),
        ),
    ]
