# Generated by Django 3.0.9 on 2020-08-08 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0004_foodlist_producttoday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='productToday',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Today is', verbose_name='Today is'),
        ),
    ]
