# Generated by Django 3.0.9 on 2020-08-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0005_auto_20200808_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='fruitList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruitName', models.TextField()),
                ('fruitCategory', models.TextField()),
            ],
        ),
    ]
