# Generated by Django 3.0.9 on 2020-08-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0006_fruitlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fruitList',
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='productCategory',
            field=models.CharField(choices=[('meat', 'MEAT'), ('fruit', 'FRUIT'), ('vegetables', 'VEGETABLES'), ('fish', 'FISH'), ('pasta', 'PASTA')], default='meat', max_length=10),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='productName',
            field=models.CharField(max_length=100),
        ),
    ]
