# Generated by Django 3.0.9 on 2020-08-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0007_auto_20200808_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='productCategory',
            field=models.CharField(choices=[('meat', 'MEAT'), ('fruit', 'FRUIT'), ('vegetables', 'VEGETABLES'), ('fish', 'FISH'), ('pasta', 'PASTA')], default='meat', help_text='The type of food', max_length=10, verbose_name='Product category'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='productName',
            field=models.CharField(help_text='The name of the product', max_length=100, verbose_name='Product name'),
        ),
    ]
