# Generated by Django 3.0.9 on 2020-08-09 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0008_auto_20200808_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='productToday',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Today is', verbose_name='Today is'),
        ),
    ]
