# Generated by Django 3.0.9 on 2020-08-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0010_auto_20200809_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlist',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='productToday',
            field=models.DateTimeField(auto_now=True, help_text='Today is', verbose_name='Today is'),
        ),
    ]
