# Generated by Django 3.0.9 on 2020-08-09 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0011_auto_20200809_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlist',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='foodlist',
            name='productToday',
        ),
        migrations.AddField(
            model_name='foodlist',
            name='todayIs',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 11, 13, 2, 888303)),
        ),
    ]
