# Generated by Django 3.0.9 on 2020-08-09 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0012_auto_20200809_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlist',
            name='status',
            field=models.CharField(choices=[('good', 'GOOD'), ('expired', 'EXPIRED')], default='good', help_text='If the product is good to eat', max_length=7, verbose_name='Product status'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='todayIs',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 11, 33, 28, 702930), help_text='Actual day', verbose_name='Today is'),
        ),
    ]
