# Generated by Django 3.0.9 on 2020-08-09 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0013_auto_20200809_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='todayIs',
            field=models.DateField(default=datetime.date(2020, 8, 9), help_text='Actual day', verbose_name='Today is'),
        ),
    ]
