# Generated by Django 3.0.9 on 2020-08-09 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0015_remove_foodlist_todayis'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlist',
            name='todayIs',
            field=models.DateField(default=django.utils.timezone.now, help_text='Check if the product is good to eat', verbose_name='Today is'),
            preserve_default=False,
        ),
    ]
