# Generated by Django 3.0.9 on 2020-08-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0016_foodlist_todayis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlist',
            name='status',
        ),
    ]
