# Generated by Django 3.0.9 on 2020-08-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0017_remove_foodlist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='productName',
            field=models.CharField(help_text='The name of the product', max_length=30, verbose_name='Product name'),
        ),
    ]
