# Generated by Django 3.0.9 on 2020-08-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0018_auto_20200810_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlist',
            name='productPrice',
            field=models.DecimalField(decimal_places=2, default=2, help_text='The price of the single product', max_digits=10, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
