# Generated by Django 3.0.9 on 2020-08-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0019_foodlist_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlist',
            name='productName_en',
            field=models.CharField(help_text='The name of the product', max_length=30, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='foodlist',
            name='productName_it',
            field=models.CharField(help_text='The name of the product', max_length=30, null=True, verbose_name='Product name'),
        ),
    ]
