# Generated by Django 3.0.9 on 2020-08-10 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0020_auto_20200810_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlist',
            name='productName_en',
        ),
        migrations.RemoveField(
            model_name='foodlist',
            name='productName_it',
        ),
    ]
