# Generated by Django 3.0.9 on 2020-08-12 23:01

from django.db import migrations
import tagging_autocomplete_new.models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0023_auto_20200813_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='productName',
            field=tagging_autocomplete_new.models.TagAutocompleteField(blank=True, help_text='The name of the product', max_length=30, verbose_name='Product name'),
        ),
    ]
