# Generated by Django 3.0.9 on 2020-08-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0025_auto_20200814_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='todayIs',
            field=models.DateField(auto_now=True, help_text='Check if the product is good to eat', verbose_name='Today is'),
        ),
    ]
