# Generated by Django 3.0.9 on 2020-08-13 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0027_auto_20200814_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='todayIs',
            field=models.DateField(blank=True, default=datetime.date(2020, 8, 14), help_text='Check if the product is good to eat', verbose_name='Today is'),
        ),
    ]
