# Generated by Django 3.0.9 on 2020-08-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0031_auto_20200819_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlist',
            name='productStatus',
            field=models.CharField(choices=[('good', 'GOOD'), ('expired', 'EXPIRED')], default='good', max_length=10, verbose_name='Product status'),
        ),
    ]
