# Generated by Django 3.0.9 on 2020-08-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0033_auto_20200820_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='productStatus',
            field=models.CharField(choices=[('good', 'GOOD'), ('expired', 'EXPIRED')], default='expired', max_length=10, verbose_name='Product status'),
        ),
    ]
