# Generated by Django 3.0.9 on 2020-08-21 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0035_auto_20200820_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodlist',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
