# Generated by Django 3.0.9 on 2020-08-21 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0036_auto_20200821_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='foodlist',
            name='modified_at',
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='todayIs',
            field=models.DateField(blank=True, default=datetime.datetime.now, editable=False, help_text='This will be helpful to calculate the expiration date', verbose_name='Today is'),
        ),
    ]
