# Generated by Django 3.0.9 on 2020-08-21 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0037_auto_20200821_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='todayIs',
            field=models.DateField(blank=True, default=datetime.datetime.now, help_text='This will be helpful to calculate the expiration date', verbose_name='Today is'),
        ),
    ]
