# Generated by Django 3.0.9 on 2020-08-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0038_auto_20200821_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlist',
            name='productBuyDate',
        ),
    ]
