# Generated by Django 3.0.9 on 2020-08-22 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0039_remove_foodlist_productbuydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='todayIs',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='This will be helpful to calculate the expiration date', verbose_name='Today is'),
        ),
    ]
