# Generated by Django 3.0.9 on 2020-08-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0044_auto_20200822_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlist',
            name='productImg',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Product image'),
        ),
    ]
