# Generated by Django 3.0.9 on 2020-08-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0048_foodlist_productimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlist',
            name='productImg',
        ),
    ]
