# Generated by Django 3.0.9 on 2020-08-22 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0049_remove_foodlist_productimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='productCategory',
            field=models.CharField(choices=[('meat', 'MEAT'), ('fish', 'FISH'), ('fruit', 'FRUIT'), ('vegetables', 'VEGETABLES'), ('pasta', 'PASTA'), ('cheese', 'CHEESE')], default='meat', help_text='The type of food', max_length=10, verbose_name='Product category'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='todayIs',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='This will be helpful to calculate the expiration date', verbose_name='Today is'),
        ),
    ]
