# Generated by Django 3.0.9 on 2020-08-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0051_foodlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlist',
            name='user',
        ),
    ]
