# Generated by Django 3.0.9 on 2020-08-23 20:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0056_remove_foodlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlist',
            name='productNotes',
            field=tinymce.models.HTMLField(default='...', verbose_name='Additional notes'),
        ),
    ]
