# Generated by Django 3.0.9 on 2020-08-23 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0057_foodlist_productnotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlist',
            name='productNotes',
        ),
    ]
