# Generated by Django 3.0.9 on 2020-08-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRecipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.CharField(help_text='The name of the recipe', max_length=30, verbose_name='Recipe name')),
            ],
        ),
    ]
