# Generated by Django 3.0.9 on 2020-08-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecipes',
            name='recipeName',
            field=models.CharField(help_text='The name of the recipe', max_length=30, unique=True, verbose_name='Recipe name'),
        ),
    ]
