# Generated by Django 3.0.9 on 2020-08-12 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodrecipes',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='foodrecipes',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodrecipes',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodrecipes',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='foodrecipes',
            name='recipeContent',
            field=models.TextField(default='-', help_text='Write here your recipe', verbose_name='Recipe content'),
        ),
        migrations.AddField(
            model_name='foodrecipes',
            name='slug',
            field=models.SlugField(default='-', max_length=250, unique_for_date='publish'),
        ),
        migrations.AddField(
            model_name='foodrecipes',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='foodrecipes',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
