# Generated by Django 3.0.9 on 2020-08-11 15:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_auto_20200811_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodrecipes',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='foodrecipes',
            name='author',
            field=models.ForeignKey(default=datetime.datetime(2020, 8, 11, 15, 10, 48, 213088, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, related_name='blog_recipes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodrecipes',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 8, 11, 15, 11, 6, 927048, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodrecipes',
            name='recipeContent',
            field=models.TextField(default=datetime.datetime(2020, 8, 11, 15, 11, 59, 382775, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodrecipes',
            name='recipeSlug',
            field=models.SlugField(default=datetime.datetime(2020, 8, 11, 15, 12, 11, 170688, tzinfo=utc), help_text='The slug URL', max_length=200, unique=True, verbose_name='Recipe slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodrecipes',
            name='recipeStatus',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
        migrations.AddField(
            model_name='foodrecipes',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
