# Generated by Django 3.0.9 on 2020-08-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200812_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrecipes',
            name='imgRecipe',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
