# Generated by Django 3.0.9 on 2020-08-12 20:27

from django.db import migrations
import editorjs_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_foodrecipes_imgrecipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodrecipes',
            name='recipeContent',
        ),
        migrations.AddField(
            model_name='foodrecipes',
            name='content',
            field=editorjs_field.fields.EditorJSField(default='Get inspired', verbose_name='Recipe content'),
        ),
    ]
