# Generated by Django 3.0.9 on 2020-08-12 21:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20200812_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodrecipes',
            name='content',
        ),
        migrations.AddField(
            model_name='foodrecipes',
            name='textRecipe',
            field=tinymce.models.HTMLField(default='Get inspired', verbose_name='Recipe content'),
        ),
    ]
