# Generated by Django 3.0.9 on 2020-08-11 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20200811_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodrecipes',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='foodrecipes',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodrecipes',
            name='recipeContent',
            field=models.TextField(default='Write here..', help_text='Write here your recipe', verbose_name='Recipe content'),
        ),
        migrations.AddField(
            model_name='foodrecipes',
            name='recipeSlug',
            field=models.SlugField(default='your-url', help_text='The slug URL', max_length=200, verbose_name='Recipe slug'),
        ),
        migrations.AddField(
            model_name='foodrecipes',
            name='recipeStatus',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
        migrations.AddField(
            model_name='foodrecipes',
            name='updated_on',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Updated On'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodrecipes',
            name='recipeName',
            field=models.CharField(help_text='The name of the recipe', max_length=30, verbose_name='Recipe name'),
        ),
    ]
