# Generated by Django 3.0.9 on 2020-08-12 22:35

from django.db import migrations
import tagging_autocomplete_new.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20200812_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrecipes',
            name='ingredientsRecipe',
            field=tagging_autocomplete_new.models.TagAutocompleteField(blank=True, help_text='Put the ingredients comma separated. \n Ex. mushrooms, tomatoes,', max_length=255, verbose_name='Ingredients'),
        ),
    ]
