# Generated by Django 3.0.9 on 2020-08-11 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20200811_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodrecipes',
            options={},
        ),
        migrations.RemoveField(
            model_name='foodrecipes',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='foodrecipes',
            name='recipeContent',
        ),
        migrations.RemoveField(
            model_name='foodrecipes',
            name='recipeSlug',
        ),
        migrations.RemoveField(
            model_name='foodrecipes',
            name='recipeStatus',
        ),
        migrations.RemoveField(
            model_name='foodrecipes',
            name='updated_on',
        ),
    ]
