# Generated by Django 3.0.9 on 2020-08-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20200813_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecipes',
            name='recipeName',
            field=models.CharField(blank=True, help_text='The name of the recipe', max_length=30, verbose_name='Recipe name'),
        ),
    ]
