# Generated by Django 3.0.9 on 2020-08-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20200814_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecipes',
            name='imgRecipe',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Recipe image'),
        ),
    ]
