# Generated by Django 3.0.9 on 2020-08-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20200819_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecipes',
            name='ingredientsRecipe',
            field=models.CharField(help_text='Put the ingredients comma separated. Ex. mushrooms, tomatoes,', max_length=30, verbose_name='Ingredients'),
        ),
    ]
