# Generated by Django 3.0.9 on 2020-08-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20200820_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecipes',
            name='imgRecipe',
            field=models.ImageField(null=True, upload_to='foodlist', verbose_name='Recipe image'),
        ),
    ]
